# Generated by Django 2.2.6 on 2019-12-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_frame', models.IntegerField(blank=True, null=True)),
                ('fin_frame', models.IntegerField(blank=True, null=True)),
                ('init_time', models.TimeField(help_text='H:M:S')),
                ('fin_time', models.TimeField(help_text='H:M:S')),
                ('frequency', models.CharField(choices=[('1 f/s', '1 f/s'), ('5 f/s', '5 f/s'), ('10 f/s', '10 f/s'), ('25 f/s', '25 f/s')], default='5 f/s', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('athlete', models.CharField(max_length=100)),
                ('csv', models.FileField(upload_to='csv_files/')),
                ('init_time', models.TimeField(help_text='H:M:S')),
                ('fin_time', models.TimeField(help_text='H:M:S')),
                ('frequency', models.CharField(choices=[('1 f/s', '1 f/s'), ('5 f/s', '5 f/s'), ('10 f/s', '10 f/s'), ('25 f/s', '25 f/s')], default='5 f/s', max_length=10, unique=True)),
            ],
        ), migrations.AlterField(
            model_name='configurationsettings',
            name='fin_frame',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configurationsettings',
            name='init_frame',
            field=models.PositiveIntegerField(blank=True, null=True),
        ), migrations.AlterField(
            model_name='performancedata',
            name='csv',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='frequency',
            field=models.CharField(choices=[('1 f/s', '1 f/s'), ('5 f/s', '5 f/s'), ('10 f/s', '10 f/s'), ('25 f/s', '25 f/s')], default='5 f/s', max_length=10),
        ),  migrations.RemoveField(
            model_name='configurationsettings',
            name='fin_time',
        ),
        migrations.RemoveField(
            model_name='configurationsettings',
            name='init_time',
        ),
        migrations.RemoveField(
            model_name='performancedata',
            name='fin_time',
        ),
        migrations.RemoveField(
            model_name='performancedata',
            name='init_time',
        ),
        migrations.AddField(
            model_name='performancedata',
            name='fin_frame',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='performancedata',
            name='init_frame',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='configurationsettings',
            name='fin_frame',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='configurationsettings',
            name='frequency',
            field=models.CharField(choices=[('1 f/s', '1 f/s'), ('5 f/s', '5 f/s'), ('10 f/s', '10 f/s'), ('25 f/s', '25 f/s')], default='5 f/s', max_length=10),
        ),
        migrations.AlterField(
            model_name='configurationsettings',
            name='init_frame',
            field=models.PositiveIntegerField(null=True),
        ), migrations.AlterField(
            model_name='performancedata',
            name='csv',
            field=models.FileField(upload_to='csv_files/'),
        ),  migrations.CreateModel(
            name='LoadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('athlete', models.CharField(max_length=100)),
                ('csv', models.FileField(upload_to='csv_files/')),
                ('init_time_ms', models.PositiveIntegerField(help_text='Time in milliseconds', null=True)),
                ('fin_time_ms', models.PositiveIntegerField(help_text='Time in milliseconds', null=True)),
                ('event_file', models.BooleanField(help_text='Events file?', null=True)),
                ('frequency', models.CharField(choices=[('1 Hz', 1), ('5 Hz', 5), ('10 Hz', 10), ('25 Hz', 25), ('100 Hz', 100), ('1000 Hz', 1000)], default='5 Hz', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='PerformanceData',
        ),
        migrations.RemoveField(
            model_name='configurationsettings',
            name='fin_frame',
        ),
        migrations.RemoveField(
            model_name='configurationsettings',
            name='init_frame',
        ),
        migrations.AlterField(
            model_name='configurationsettings',
            name='frequency',
            field=models.CharField(choices=[('1 Hz', 1), ('5 Hz', 5), ('10 Hz', 10), ('25 Hz', 25), ('100 Hz', 100), ('1000 Hz', 1000)], default='5 Hz', help_text='Data table frequency', max_length=10),
        ),
        migrations.AlterField(
            model_name='configurationsettings',
            name='frequency',
            field=models.CharField(
                choices=[(1, '1 Hz'), (5, '5 Hz'), (10, '10 Hz'), (25, '25 Hz'), (100, '100 Hz'), (1000, '1000 Hz')],
                default=5, help_text='Data table frequency', max_length=10),
        ),
        migrations.AlterField(
            model_name='loaddata',
            name='event_file',
            field=models.BooleanField(choices=[('Yes', True), ('No', False)], default='Yes', help_text='Events file?',
                                      null=True),
        ),
        migrations.AlterField(
            model_name='loaddata',
            name='event_file',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default='Yes', help_text='Events file?',
                                      null=True),
        ),
        migrations.AlterField(
            model_name='loaddata',
            name='frequency',
            field=models.IntegerField(
                choices=[('1 Hz', 1), ('5 Hz', 5), ('10 Hz', 10), ('25 Hz', 25), ('100 Hz', 100), ('1000 Hz', 1000)],
                default='5 Hz', max_length=10),
        ),
        migrations.AlterField(
            model_name='configurationsettings',
            name='frequency',
            field=models.IntegerField(
                choices=[(1, '1 Hz'), (5, '5 Hz'), (10, '10 Hz'), (25, '25 Hz'), (100, '100 Hz'), (1000, '1000 Hz')],
                default=5, help_text='Data table frequency'),
        ),
        migrations.AlterField(
            model_name='loaddata',
            name='frequency',
            field=models.IntegerField(
                choices=[(1, '1 Hz'), (5, '5 Hz'), (10, '10 Hz'), (25, '25 Hz'), (100, '100 Hz'), (1000, '1000 Hz')],
                default=5),
        ),
        migrations.AlterField(
            model_name='loaddata',
            name='event_file',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Events file?',
                                      null=True),
        ),
        migrations.AlterField(
            model_name='loaddata',
            name='event_file',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=(True, 'Yes'),
                                      help_text='Events file?', null=True),
        ),
        migrations.AlterField(
            model_name='loaddata',
            name='event_file',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0, help_text='Events file?', null=True),
        ),
    ]
