# Generated by Django 2.2.6 on 2020-01-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(choices=[(1, '1 Hz'), (5, '5 Hz'), (10, '10 Hz'), (25, '25 Hz'), (100, '100 Hz'), (1000, '1000 Hz')], default=5, help_text='Data table frequency')),
            ],
        ),
        migrations.CreateModel(
            name='LoadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('athlete', models.CharField(max_length=100)),
                ('csv', models.FileField(upload_to='csv_files/')),
                ('init_time_ms', models.PositiveIntegerField(help_text='Time in milliseconds', null=True)),
                ('fin_time_ms', models.PositiveIntegerField(help_text='Time in milliseconds', null=True)),
                ('event_file', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0, help_text='Events file?', null=True)),
                ('frequency', models.IntegerField(choices=[(1, '1 Hz'), (5, '5 Hz'), (10, '10 Hz'), (25, '25 Hz'), (100, '100 Hz'), (1000, '1000 Hz')], default=5)),
            ],
        ),
    ]
