# Generated by Django 2.2.6 on 2020-01-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationsettings',
            name='fin_frame',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configurationsettings',
            name='init_frame',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
