# Generated by Django 2.2.6 on 2020-04-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordeventsfile',
            name='chart_perf_vars',
            field=models.TextField(blank=True, help_text='Performance variables separated by comma for showing their data to the chart data.', max_length=250),
        ),
    ]
