# Generated by Django 2.2.6 on 2020-02-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaddata',
            name='fin_time_ms',
        ),
        migrations.RemoveField(
            model_name='loaddata',
            name='init_time_ms',
        ),
        migrations.AddField(
            model_name='configurationsetting',
            name='fin_time_ms',
            field=models.PositiveIntegerField(help_text='Time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='configurationsetting',
            name='init_time_ms',
            field=models.PositiveIntegerField(help_text='Time in milliseconds', null=True),
        ),
    ]
