# Generated by Django 2.2.6 on 2020-03-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWordDevicesFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_name', models.CharField(help_text='Column name of Time of DEVICES files.', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeyWordEventsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_ms_name', models.CharField(help_text='Column name of Time in milli-seconds values.', max_length=100, null=True)),
                ('duration_time_ms_name', models.CharField(help_text='Column name of Time Duration in milli-seconds values.', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='KeyWord',
        ),
        migrations.AlterField(
            model_name='loaddata',
            name='frequency',
            field=models.IntegerField(choices=[(0, ''), (1, '1 Hz'), (5, '5 Hz'), (10, '10 Hz'), (25, '25 Hz'), (100, '100 Hz'), (1000, '1000 Hz')], default=0, help_text='Ignore the field when uploading EVENTS file.'),
        ),
    ]
