# Generated by Django 2.2.6 on 2020-02-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200211_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsetting',
            name='duration_time_ms_name',
            field=models.CharField(help_text='Column name of Time Duration (milli-seconds) values (events file)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configurationsetting',
            name='time_ms_name',
            field=models.CharField(help_text='Column name of Time (milli-seconds) values (events file)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loaddata',
            name='athlete',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='loaddata',
            name='event_file',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0, help_text='Events file?'),
        ),
        migrations.AlterField(
            model_name='loaddata',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
