# Generated by Django 2.2.6 on 2020-01-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200114_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancedata',
            name='csv',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='frequency',
            field=models.CharField(choices=[('1 f/s', '1 f/s'), ('5 f/s', '5 f/s'), ('10 f/s', '10 f/s'), ('25 f/s', '25 f/s')], default='5 f/s', max_length=10),
        ),
    ]
