# Generated by Django 2.2.6 on 2020-04-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200417_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordeventsfile',
            name='chart_perf_vars',
            field=models.TextField(blank=True, help_text='Performance variables separated by comma for showing their data to the chart data. Use white spaces if you like.', max_length=250),
        ),
    ]
