# Generated by Django 2.2.6 on 2020-03-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200224_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationsetting',
            name='duration_time_ms_name',
            field=models.CharField(help_text='Column name of Time Duration (milli-seconds) values (events file).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configurationsetting',
            name='fin_time_ms',
            field=models.PositiveIntegerField(help_text='Time in milliseconds.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationsetting',
            name='init_time_ms',
            field=models.PositiveIntegerField(help_text='Time in milliseconds.', null=True),
        ),
        migrations.AlterField(
            model_name='configurationsetting',
            name='time_ms_name',
            field=models.CharField(help_text='Column name of Time (milli-seconds) values (events file).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loaddata',
            name='event_file',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0, help_text='Is it events file?'),
        ),
        migrations.AlterField(
            model_name='loaddata',
            name='frequency',
            field=models.IntegerField(choices=[(0, ''), (1, '1 Hz'), (5, '5 Hz'), (10, '10 Hz'), (25, '25 Hz'), (100, '100 Hz'), (1000, '1000 Hz')], default=0, help_text='Ignore field when uploading events file.'),
        ),
    ]
