# Generated by Django 2.2.6 on 2020-01-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200120_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationsettings',
            name='fin_time',
        ),
        migrations.RemoveField(
            model_name='configurationsettings',
            name='init_time',
        ),
        migrations.RemoveField(
            model_name='performancedata',
            name='fin_time',
        ),
        migrations.RemoveField(
            model_name='performancedata',
            name='init_time',
        ),
        migrations.AddField(
            model_name='performancedata',
            name='fin_frame',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='performancedata',
            name='init_frame',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='configurationsettings',
            name='fin_frame',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='configurationsettings',
            name='frequency',
            field=models.CharField(choices=[('1 f/s', '1 f/s'), ('5 f/s', '5 f/s'), ('10 f/s', '10 f/s'), ('25 f/s', '25 f/s')], default='5 f/s', max_length=10),
        ),
        migrations.AlterField(
            model_name='configurationsettings',
            name='init_frame',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
