# Generated by Django 2.2.6 on 2020-04-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200417_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordeventsfile',
            name='chart_perf_vars',
            field=models.TextField(blank=True, help_text='Performance variables separated by comma for showing their data to the chart data. Use white spaces if you like. Please put the variables in the same order as they are shown.', max_length=250),
        ),
    ]
