# Generated by Django 2.2.6 on 2020-01-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200120_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancedata',
            name='csv',
            field=models.FileField(upload_to='csv_files/'),
        ),
    ]
