# Generated by Django 2.2.6 on 2020-01-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200120_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('athlete', models.CharField(max_length=100)),
                ('csv', models.FileField(upload_to='csv_files/')),
                ('init_time_ms', models.PositiveIntegerField(help_text='Time in milliseconds', null=True)),
                ('fin_time_ms', models.PositiveIntegerField(help_text='Time in milliseconds', null=True)),
                ('event_file', models.BooleanField(help_text='Events file?', null=True)),
                ('frequency', models.CharField(choices=[('1 Hz', 1), ('5 Hz', 5), ('10 Hz', 10), ('25 Hz', 25), ('100 Hz', 100), ('1000 Hz', 1000)], default='5 Hz', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='PerformanceData',
        ),
        migrations.RemoveField(
            model_name='configurationsettings',
            name='fin_frame',
        ),
        migrations.RemoveField(
            model_name='configurationsettings',
            name='init_frame',
        ),
        migrations.AlterField(
            model_name='configurationsettings',
            name='frequency',
            field=models.CharField(choices=[('1 Hz', 1), ('5 Hz', 5), ('10 Hz', 10), ('25 Hz', 25), ('100 Hz', 100), ('1000 Hz', 1000)], default='5 Hz', help_text='Data table frequency', max_length=10),
        ),
    ]
