# Generated by Django 2.2.6 on 2020-03-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200314_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_ms_name', models.CharField(help_text='Column name of Time in milli-seconds values (events file).', max_length=100, null=True)),
                ('duration_time_ms_name', models.CharField(help_text='Column name of Time Duration in milli-seconds values (events file).', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='configurationsetting',
            name='duration_time_ms_name',
        ),
        migrations.RemoveField(
            model_name='configurationsetting',
            name='time_ms_name',
        ),
    ]
