# Generated by Django 2.2.6 on 2020-01-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200128_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaddata',
            name='event_file',
            field=models.BooleanField(choices=[('Yes', True), ('No', False)], default='Yes', help_text='Events file?', null=True),
        ),
    ]
