# Generated by Django 2.2.6 on 2020-01-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200128_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaddata',
            name='frequency',
            field=models.IntegerField(choices=[('1 Hz', 1), ('5 Hz', 5), ('10 Hz', 10), ('25 Hz', 25), ('100 Hz', 100), ('1000 Hz', 1000)], default='5 Hz', max_length=10),
        ),
    ]
