# Generated by Django 2.2.6 on 2020-01-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200128_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationsettings',
            name='frequency',
            field=models.IntegerField(choices=[(1, '1 Hz'), (5, '5 Hz'), (10, '10 Hz'), (25, '25 Hz'), (100, '100 Hz'), (1000, '1000 Hz')], default=5, help_text='Data table frequency'),
        ),
        migrations.AlterField(
            model_name='loaddata',
            name='frequency',
            field=models.IntegerField(choices=[(1, '1 Hz'), (5, '5 Hz'), (10, '10 Hz'), (25, '25 Hz'), (100, '100 Hz'), (1000, '1000 Hz')], default=5),
        ),
    ]
