# Generated by Django 2.2.6 on 2020-01-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200129_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaddata',
            name='event_file',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=(True, 'Yes'), help_text='Events file?', null=True),
        ),
    ]
