# Generated by Django 2.2.6 on 2020-01-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200129_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaddata',
            name='event_file',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0, help_text='Events file?', null=True),
        ),
    ]
